services:

  mariadb:
    image: mariadb
    container_name: iam_mdb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: apirootpwd
      MARIADB_USER: apiuser
      MARIADB_PASSWORD: apipwd
      MARIADB_DATABASE: iam
    ports:
      - 13306:3306
    volumes:
      - ./deploy/docker-data/mariadb/data_1:/var/lib/mysql:rw
      - ./deploy/docker-data/mariadb/sql:/docker-entrypoint-initdb.d


  # adminer:
  #   image: adminer
  #   container_name: iam_mdb_adminer
  #   restart: always
  #   ports:
  #     - 18080:8080

  # redis:
  #   image: "redis:latest"
  #   container_name: iam_redis
  #   ports:
  #     - "6379:6379"

  # mongodb:
  #   image: mongo
  #   container_name: iam-mongodb-container
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   command: [--auth]
  #   environment:
  #     TZ: Asia/Shanghai
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: adminpwd
  #   volumes:
  #     - ./deploy/docker-data/mongodb/data_1:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: iam-mongo-express
  #   ports:
  #     - '27018:8081'
  #   environment:
  #     ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: adminpwd
  #     ME_CONFIG_BASICAUTH_USERNAME: iamadmin
  #     ME_CONFIG_BASICAUTH_PASSWORD: iampwd
  #   depends_on:
  #     - mongodb